export const FETCH = 'FETCH'
export const ADD_ALL = 'ADD_ALL'
export const REMOVE = 'REMOVE'
export const REMOVE_ALL = 'REMOVE_ALL'
export const ERROR = 'ERROR'
export const ADD = 'ADD'
export const CHANGE = 'CHANGE'
